language: ruby

addons:
  postgresql: 9.4

rvm:
  - 2.2.2
  - 2.2.3
  - 2.2.4

env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000

sudo: false

cache: bundler

before_script:
  - cp config/database.yml.ci config/database.yml
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace

bundler_args: "--without development --jobs 3 --retry 5"

script:
  - RAILS_ENV=test bundle exec rspec

notifications:
  email: false
